[package]
name = "nestum"
version = "0.2.2"
edition = "2024"
description = "Proc-macro for nested enum paths like Enum1::Variant1::VariantA"
license = "MIT"
repository = "https://github.com/eboody/nestum"
readme = "../README.md"

[lib]
proc-macro = true

[dependencies]
darling = "0.21"
module_path_extractor = "0.3.16"
proc-macro2 = { version = "1", features = ["span-locations"] }
proc-macro-error2 = "2"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits", "visit-mut"] }

[dev-dependencies]
prettyplease = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
trybuild = "1"
